from app.models import db, Note


# Adds a demo user, you can add other users here if you want
def seed_Notes():
    one = Note(
        title='flask', body=" # This is a heading ## This is a slightly smaller heading \ - [ ] Hi, I’m a todo list item - [ ] You can click this box when not in edit mode as well! \ * add some bullets 1. or numbers \ ## if you *highlight* your ==text==, you can [format](https://www.google.com) it. **Highlight** this in edit mode! | some | thing | wicked | |----|----|----| | this | way | comes | \ > This is a quote! \ ```javascript hover this code block and choose which language to write it in! ``` \ --- \ ![If you know how to add a picture in markdown syntax, you can!](https://i.ibb.co/b7NqqXL/Soft-clouds-of-colorful-smoke-dark-abstract-background.jpg) \ \ :::info This is an important notice! ::: :::warning This is a warning! ::: :::tip This is a quick tip! ::: \ ", userId='1', notebookId='1', share=True)
    two = Note(
        title='sqlalchemy', body="# This is a heading ## This is a slightly smaller heading \ - [ ] Hi, I’m a todo list item - [ ] You can click this box when not in edit mode as well! \ * add some bullets 1. or numbers \ ## if you *highlight* your ==text==, you can [format](https://www.google.com) it. **Highlight** this in edit mode! | some | thing | wicked | |----|----|----| | this | way | comes | \ > This is a quote! \ ```javascript hover this code block and choose which language to write it in! ``` \ --- \ ![If you know how to add a picture in markdown syntax, you can!](https://i.ibb.co/b7NqqXL/Soft-clouds-of-colorful-smoke-dark-abstract-background.jpg) \ \ :::info This is an important notice! ::: :::warning This is a warning! ::: :::tip This is a quick tip! ::: \ ", userId='1', notebookId='1')
    three = Note(
        title='wtforms', body="# This is a heading ## This is a slightly smaller heading \ - [ ] Hi, I’m a todo list item - [ ] You can click this box when not in edit mode as well! \ * add some bullets 1. or numbers \ ## if you *highlight* your ==text==, you can [format](https://www.google.com) it. **Highlight** this in edit mode! | some | thing | wicked | |----|----|----| | this | way | comes | \ > This is a quote! \ ```javascript hover this code block and choose which language to write it in! ``` \ --- \ ![If you know how to add a picture in markdown syntax, you can!](https://i.ibb.co/b7NqqXL/Soft-clouds-of-colorful-smoke-dark-abstract-background.jpg) \ \ :::info This is an important notice! ::: :::warning This is a warning! ::: :::tip This is a quick tip! ::: \ ", userId='1', notebookId='1', share=True)
    four = Note(
        title='actions', body="# This is a heading ## This is a slightly smaller heading \ - [ ] Hi, I’m a todo list item - [ ] You can click this box when not in edit mode as well! \ * add some bullets 1. or numbers \ ## if you *highlight* your ==text==, you can [format](https://www.google.com) it. **Highlight** this in edit mode! | some | thing | wicked | |----|----|----| | this | way | comes | \ > This is a quote! \ ```javascript hover this code block and choose which language to write it in! ``` \ --- \ ![If you know how to add a picture in markdown syntax, you can!](https://i.ibb.co/b7NqqXL/Soft-clouds-of-colorful-smoke-dark-abstract-background.jpg) \ \ :::info This is an important notice! ::: :::warning This is a warning! ::: :::tip This is a quick tip! ::: \ ", userId='1', notebookId='2')
    five = Note(
        title='thunks', body="# This is a heading ## This is a slightly smaller heading \ - [ ] Hi, I’m a todo list item - [ ] You can click this box when not in edit mode as well! \ * add some bullets 1. or numbers \ ## if you *highlight* your ==text==, you can [format](https://www.google.com) it. **Highlight** this in edit mode! | some | thing | wicked | |----|----|----| | this | way | comes | \ > This is a quote! \ ```javascript hover this code block and choose which language to write it in! ``` \ --- \ ![If you know how to add a picture in markdown syntax, you can!](https://i.ibb.co/b7NqqXL/Soft-clouds-of-colorful-smoke-dark-abstract-background.jpg) \ \ :::info This is an important notice! ::: :::warning This is a warning! ::: :::tip This is a quick tip! ::: \ ", userId='1', notebookId='2', share=True)
    six = Note(
        title='reducers', body="# This is a heading ## This is a slightly smaller heading \ - [ ] Hi, I’m a todo list item - [ ] You can click this box when not in edit mode as well! \ * add some bullets 1. or numbers \ ## if you *highlight* your ==text==, you can [format](https://www.google.com) it. **Highlight** this in edit mode! | some | thing | wicked | |----|----|----| | this | way | comes | \ > This is a quote! \ ```javascript hover this code block and choose which language to write it in! ``` \ --- \ ![If you know how to add a picture in markdown syntax, you can!](https://i.ibb.co/b7NqqXL/Soft-clouds-of-colorful-smoke-dark-abstract-background.jpg) \ \ :::info This is an important notice! ::: :::warning This is a warning! ::: :::tip This is a quick tip! ::: \ ", userId='1', notebookId='2', share=True)
    ten = Note(
        title='event listeners', body="# This is a heading ## This is a slightly smaller heading \ - [ ] Hi, I’m a todo list item - [ ] You can click this box when not in edit mode as well! \ * add some bullets 1. or numbers \ ## if you *highlight* your ==text==, you can [format](https://www.google.com) it. **Highlight** this in edit mode! | some | thing | wicked | |----|----|----| | this | way | comes | \ > This is a quote! \ ```javascript hover this code block and choose which language to write it in! ``` \ --- \ ![If you know how to add a picture in markdown syntax, you can!](https://i.ibb.co/b7NqqXL/Soft-clouds-of-colorful-smoke-dark-abstract-background.jpg) \ \ :::info This is an important notice! ::: :::warning This is a warning! ::: :::tip This is a quick tip! ::: \ ", userId='2', notebookId='4')
    seven = Note(
        title='overview', body="# This is a heading ## This is a slightly smaller heading \ - [ ] Hi, I’m a todo list item - [ ] You can click this box when not in edit mode as well! \ * add some bullets 1. or numbers \ ## if you *highlight* your ==text==, you can [format](https://www.google.com) it. **Highlight** this in edit mode! | some | thing | wicked | |----|----|----| | this | way | comes | \ > This is a quote! \ ```javascript hover this code block and choose which language to write it in! ``` \ --- \ ![If you know how to add a picture in markdown syntax, you can!](https://i.ibb.co/b7NqqXL/Soft-clouds-of-colorful-smoke-dark-abstract-background.jpg) \ \ :::info This is an important notice! ::: :::warning This is a warning! ::: :::tip This is a quick tip! ::: \ ", userId='2', notebookId='5', share=True)
    eight = Note(
        title='quickRef', body="# This is a heading ## This is a slightly smaller heading \ - [ ] Hi, I’m a todo list item - [ ] You can click this box when not in edit mode as well! \ * add some bullets 1. or numbers \ ## if you *highlight* your ==text==, you can [format](https://www.google.com) it. **Highlight** this in edit mode! | some | thing | wicked | |----|----|----| | this | way | comes | \ > This is a quote! \ ```javascript hover this code block and choose which language to write it in! ``` \ --- \ ![If you know how to add a picture in markdown syntax, you can!](https://i.ibb.co/b7NqqXL/Soft-clouds-of-colorful-smoke-dark-abstract-background.jpg) \ \ :::info This is an important notice! ::: :::warning This is a warning! ::: :::tip This is a quick tip! ::: \ ", userId='2', notebookId='5', share=True)
    nine = Note(
        title='advanced array methods', body="# This is a heading ## This is a slightly smaller heading \ - [ ] Hi, I’m a todo list item - [ ] You can click this box when not in edit mode as well! \ * add some bullets 1. or numbers \ ## if you *highlight* your ==text==, you can [format](https://www.google.com) it. **Highlight** this in edit mode! | some | thing | wicked | |----|----|----| | this | way | comes | \ > This is a quote! \ ```javascript hover this code block and choose which language to write it in! ``` \ --- \ ![If you know how to add a picture in markdown syntax, you can!](https://i.ibb.co/b7NqqXL/Soft-clouds-of-colorful-smoke-dark-abstract-background.jpg) \ \ :::info This is an important notice! ::: :::warning This is a warning! ::: :::tip This is a quick tip! ::: \ ", userId='3', notebookId='8', share=True)
    eleven = Note(
        title='matrix', body="# This is a heading ## This is a slightly smaller heading \ - [ ] Hi, I’m a todo list item - [ ] You can click this box when not in edit mode as well! \ * add some bullets 1. or numbers \ ## if you *highlight* your ==text==, you can [format](https://www.google.com) it. **Highlight** this in edit mode! | some | thing | wicked | |----|----|----| | this | way | comes | \ > This is a quote! \ ```javascript hover this code block and choose which language to write it in! ``` \ --- \ ![If you know how to add a picture in markdown syntax, you can!](https://i.ibb.co/b7NqqXL/Soft-clouds-of-colorful-smoke-dark-abstract-background.jpg) \ \ :::info This is an important notice! ::: :::warning This is a warning! ::: :::tip This is a quick tip! ::: \ ", userId='3', notebookId='8')
    twelve = Note(
        title='for loops', body="# This is a heading ## This is a slightly smaller heading \ - [ ] Hi, I’m a todo list item - [ ] You can click this box when not in edit mode as well! \ * add some bullets 1. or numbers \ ## if you *highlight* your ==text==, you can [format](https://www.google.com) it. **Highlight** this in edit mode! | some | thing | wicked | |----|----|----| | this | way | comes | \ > This is a quote! \ ```javascript hover this code block and choose which language to write it in! ``` \ --- \ ![If you know how to add a picture in markdown syntax, you can!](https://i.ibb.co/b7NqqXL/Soft-clouds-of-colorful-smoke-dark-abstract-background.jpg) \ \ :::info This is an important notice! ::: :::warning This is a warning! ::: :::tip This is a quick tip! ::: \ ", userId='3', notebookId='8', share=True)
    thirteen = Note(
        title='variables', body="# This is a heading ## This is a slightly smaller heading \ - [ ] Hi, I’m a todo list item - [ ] You can click this box when not in edit mode as well! \ * add some bullets 1. or numbers \ ## if you *highlight* your ==text==, you can [format](https://www.google.com) it. **Highlight** this in edit mode! | some | thing | wicked | |----|----|----| | this | way | comes | \ > This is a quote! \ ```javascript hover this code block and choose which language to write it in! ``` \ --- \ ![If you know how to add a picture in markdown syntax, you can!](https://i.ibb.co/b7NqqXL/Soft-clouds-of-colorful-smoke-dark-abstract-background.jpg) \ \ :::info This is an important notice! ::: :::warning This is a warning! ::: :::tip This is a quick tip! ::: \ ", userId='3', notebookId='8')
    fourteen = Note(
        title='fetch', body="# This is a heading ## This is a slightly smaller heading \ - [ ] Hi, I’m a todo list item - [ ] You can click this box when not in edit mode as well! \ * add some bullets 1. or numbers \ ## if you *highlight* your ==text==, you can [format](https://www.google.com) it. **Highlight** this in edit mode! | some | thing | wicked | |----|----|----| | this | way | comes | \ > This is a quote! \ ```javascript hover this code block and choose which language to write it in! ``` \ --- \ ![If you know how to add a picture in markdown syntax, you can!](https://i.ibb.co/b7NqqXL/Soft-clouds-of-colorful-smoke-dark-abstract-background.jpg) \ \ :::info This is an important notice! ::: :::warning This is a warning! ::: :::tip This is a quick tip! ::: \ ", userId='3', notebookId='9', share=True)
    fifteen = Note(
        title='time complexity', body="# This is a heading ## This is a slightly smaller heading \ - [ ] Hi, I’m a todo list item - [ ] You can click this box when not in edit mode as well! \ * add some bullets 1. or numbers \ ## if you *highlight* your ==text==, you can [format](https://www.google.com) it. **Highlight** this in edit mode! | some | thing | wicked | |----|----|----| | this | way | comes | \ > This is a quote! \ ```javascript hover this code block and choose which language to write it in! ``` \ --- \ ![If you know how to add a picture in markdown syntax, you can!](https://i.ibb.co/b7NqqXL/Soft-clouds-of-colorful-smoke-dark-abstract-background.jpg) \ \ :::info This is an important notice! ::: :::warning This is a warning! ::: :::tip This is a quick tip! ::: \ ", userId='3', notebookId='9')
    sixteen = Note(
        title='sorts', body="# This is a heading ## This is a slightly smaller heading \ - [ ] Hi, I’m a todo list item - [ ] You can click this box when not in edit mode as well! \ * add some bullets 1. or numbers \ ## if you *highlight* your ==text==, you can [format](https://www.google.com) it. **Highlight** this in edit mode! | some | thing | wicked | |----|----|----| | this | way | comes | \ > This is a quote! \ ```javascript hover this code block and choose which language to write it in! ``` \ --- \ ![If you know how to add a picture in markdown syntax, you can!](https://i.ibb.co/b7NqqXL/Soft-clouds-of-colorful-smoke-dark-abstract-background.jpg) \ \ :::info This is an important notice! ::: :::warning This is a warning! ::: :::tip This is a quick tip! ::: \ ", userId='3', notebookId='9', share=True)
    seventeen = Note(
        title='flask', body="# This is a heading ## This is a slightly smaller heading \ - [ ] Hi, I’m a todo list item - [ ] You can click this box when not in edit mode as well! \ * add some bullets 1. or numbers \ ## if you *highlight* your ==text==, you can [format](https://www.google.com) it. **Highlight** this in edit mode! | some | thing | wicked | |----|----|----| | this | way | comes | \ > This is a quote! \ ```javascript hover this code block and choose which language to write it in! ``` \ --- \ ![If you know how to add a picture in markdown syntax, you can!](https://i.ibb.co/b7NqqXL/Soft-clouds-of-colorful-smoke-dark-abstract-background.jpg) \ \ :::info This is an important notice! ::: :::warning This is a warning! ::: :::tip This is a quick tip! ::: \ ", userId='3', notebookId='10')
    eighteen = Note(
        title='sqlalchemy', body="# This is a heading ## This is a slightly smaller heading \ - [ ] Hi, I’m a todo list item - [ ] You can click this box when not in edit mode as well! \ * add some bullets 1. or numbers \ ## if you *highlight* your ==text==, you can [format](https://www.google.com) it. **Highlight** this in edit mode! | some | thing | wicked | |----|----|----| | this | way | comes | \ > This is a quote! \ ```javascript hover this code block and choose which language to write it in! ``` \ --- \ ![If you know how to add a picture in markdown syntax, you can!](https://i.ibb.co/b7NqqXL/Soft-clouds-of-colorful-smoke-dark-abstract-background.jpg) \ \ :::info This is an important notice! ::: :::warning This is a warning! ::: :::tip This is a quick tip! ::: \ ", userId='3', notebookId='10', share=True)
    nineteen = Note(
        title='wtforms', body="# This is a heading ## This is a slightly smaller heading \ - [ ] Hi, I’m a todo list item - [ ] You can click this box when not in edit mode as well! \ * add some bullets 1. or numbers \ ## if you *highlight* your ==text==, you can [format](https://www.google.com) it. **Highlight** this in edit mode! | some | thing | wicked | |----|----|----| | this | way | comes | \ > This is a quote! \ ```javascript hover this code block and choose which language to write it in! ``` \ --- \ ![If you know how to add a picture in markdown syntax, you can!](https://i.ibb.co/b7NqqXL/Soft-clouds-of-colorful-smoke-dark-abstract-background.jpg) \ \ :::info This is an important notice! ::: :::warning This is a warning! ::: :::tip This is a quick tip! ::: \ ", userId='3', notebookId='10')

    db.session.add(one)
    db.session.add(two)
    db.session.add(three)
    db.session.add(four)
    db.session.add(five)
    db.session.add(six)
    db.session.add(seven)
    db.session.add(eight)
    db.session.add(nine)
    db.session.add(ten)
    db.session.add(eleven)
    db.session.add(twelve)
    db.session.add(thirteen)
    db.session.add(fourteen)
    db.session.add(fifteen)
    db.session.add(sixteen)
    db.session.add(seventeen)
    db.session.add(eighteen)
    db.session.add(nineteen)


    db.session.commit()


# Uses a raw SQL query to TRUNCATE the users table.
# SQLAlchemy doesn't have a built in function to do this
# TRUNCATE Removes all the data from the table, and RESET IDENTITY
# resets the auto incrementing primary key, CASCADE deletes any
# dependent entities
def undo_Notes():
    db.session.execute('TRUNCATE Notes RESTART IDENTITY CASCADE;')
    db.session.commit()